var level0 = [
		    'xxxxxxxxxxxxxxx',
		    'x             x',
		    'x             x',
		    'x   o         x',
		    'x             x',
		    'x             x',
			'x   -----     x',
		    'x             x',
		    'x             x',
		    'x             x',
		    'x-----------  x',
		    'x             x',
		    'x     o       x',
		    'x             x',
		    'x    -------  x',
		    'x             x',
		    'x             x',
		    'x  -------    x',
		    'x             x',
		    'x   o         x',
		    'x          o  x',
		    'x --          x',
		    'x         ----x',
		    'x             x',
		    'x -----       x',
			'x       o     x',
		    'x             x',
		    'x             x',
		    'x-------------x',
		];
var level1 = [
		    'xxxxxxxxxxxxxxx',
		    'x             x',
		    'x             x',
		    'x   o         x',
		    'x             x',
		    'x             x',
			'x   -----     x',
		    'x         !!!!x',
		    'x             x',
		    'x             x',
		    'x-----------  x',
		    'x             x',
		    'x     o       x',
		    'x             x',
		    'x    -------  x',
		    'x             x',
		    'x             x',
		    'x  ---- !!    x',
		    'x             x',
		    'x   o         x',
		    'x          o  x',
		    'x!   !!       x',
		    'x         ----x',
		    'x             x',
		    'x ------      x',
			'x       o     x',
		    'x             x',
		    'x             x',
		    'x-------------x',
		];

var level2 = [
		    'xxxxxxxxxxxxxxx',
		    'x             x',
		    'x             x',
		    'x        o    x',
		    'x             x',
		    'x             x',
			'x   -----     x',
		    'x   !!!!! !!!!x',
		    'x             x',
		    'x  o          x',
		    'x-----        x',
		    'x    -        x',
		    'x    - o      x',
		    'x    -        x',
		    'x    ----     x',
		    'x             x',
		    'x             x',
		    'x  ---- !!    x',
		    'x  -          x',
		    'x  -o         x',
		    'x             x',
		    'x! !!--       x',
		    'x         ----x',
		    'x             x',
		    'x ------      x',
			'x       o     x',
		    'x             x',
		    'x             x',
		    'x-------------x',
		];